name: v_tech
version: 3.0.2+3
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter:
    sdk: flutter
  simple_animations: ^4.0.0
  flutter_svg: ^0.22.0
  simple_gradient_text: ^1.2.2
  sqflite: ^2.0.0+4
  get_storage: ^2.0.3
  fl_chart: ^0.40.0
  data_table_2: ^2.1.1
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  sticky_headers: ^0.2.0
  flutter_image_compress: ^1.1.0
  image_picker: ^0.8.4+2
  carousel_slider: ^4.0.0
  http: ^0.13.4
  url_launcher: ^6.0.12
  table_calendar: ^3.0.3
  firebase_core: ^1.8.0
  firebase_messaging: ^10.0.9
  flutter_local_notifications: ^9.0.1
  firebase_database: ^8.0.1
  rxdart: ^0.27.3


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
  #           style: italic
  #     - family: Trajan Pro
  #       fonts:
  #         - asset: fonts/Avenir-Book.ttf
  #         - asset: fonts/Avenir-Heavy.ttf
  #         - asset: fonts/Avenir-Light.ttf
  #         - asser: fonts/Avenir-Medium.ttf
  #           weight: 700